spring:
  liquibase:
    change-log: classpath:db/changelog/master.yaml
    enabled: true
  datasource:
    url: jdbc:mysql://47.108.189.44:3306/xxx?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: huojie
  cloud:
    nacos:
      config:
        file-extension: yaml
        refresh-enabled: true
        server-addr: 47.108.189.44:8848
        namespace: 640b17c7-0f94-4d75-b8e5-563aa33aedfb
      discovery:
        server-addr: 47.108.189.44:8848
        namespace: 640b17c7-0f94-4d75-b8e5-563aa33aedfb


