server:
  port: 9898
spring:
  profiles:
    active: dev
  application:
    name: xxxx-server
  config:
    import:
      - optional:nacos:${spring.application.name}-dev.yaml
      - optional:classpath:/custom.yaml
  servlet:
    multipart:
      enabled: true
      max-file-size: 4GB
      max-request-size: 4GB
logging:
  file:
    path: /logs/xxx
  level:
    com.alibaba.cloud.nacos.configdata: debug
################# MyBatis配置 #################
mybatis-flex:
  mapper-locations:
    - classpath*:/mapper/*.xml
  global-config:
    normal-value-of-logic-delete: false
    deleted-value-of-logic-delete: true

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: 1800
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: simple-uuid
  # 是否输出操作日志
  is-log: true

################ springdoc-openapi项目配置 ####################
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: order
    operations-sorter: order
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.stp.xxx.api
################# knife4j的增强配置，不需要增强可以不配 ###########
knife4j:
  enable: true
  setting:
    language: zh_cn
########################## alist #############################
alist:
  server:
    host: 47.108.189.44
    port: 5244
  username: admin
  password: stophemo
######################### forest #############################
forest:
  max-connections: 1000        # 连接池最大连接数
  connect-timeout: 3000        # 连接超时时间，单位为毫秒
  read-timeout: 3000           # 数据读取超时时间，单位为毫秒
