server:
  port: 9898
spring:
  application:
    name: xxx-server
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        server-addr: 192.168.8.30:8848
        file-extension: yaml
      discovery:
        server-addr: 192.168.8.30:8848
  config:
    import:
      - nacos:xxx-server-dev.yaml
  liquibase:
    change-log: classpath:db/changelog/master.yaml
    enabled: true
################# MyBatis配置 #################
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: off
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.stp.xxx.entity

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: 1800
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: simple-uuid
  # 是否输出操作日志
  is-log: true

################ springdoc-openapi项目配置 ####################
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.stp.xxx.api
################# knife4j的增强配置，不需要增强可以不配 ###########
knife4j:
  enable: true
  setting:
    language: zh_cn

#my:
#  custom:
#    property: This is a custom property from Nacos