server:
  port: 9999
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xxx?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
logging:
  file:
    path: /logs/xxx
token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
knife4j:
  enable: true

