spring:
  application:
    name: Springboot3-Springsecurity6-Mybatisplus
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  main:
    banner-mode: off

  liquibase:
    change-log: classpath:db/changelog/master.yaml
    enabled: true

# MyBatis配置
#mybatis:
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: off
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.stp.xxx.entity

server:
  servlet:
    context-path: /stp
  shutdown: graceful

